version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: cimg/android:2021.08.1
    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: ./gradlew lint test
